version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/userServiceDB
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3002

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurantServiceDB
      - DELIVERY_SERVICE_URL=http://delivery-service:3003

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/deliveryServiceDB
